@server = http://localhost:3000/api

GET {{server}}/admins

###

POST {{server}}/admins
content-type: application/json

{
    "user": "laura.flores@nuevoamanecer.edu.mx",
    "password": "123456789Ab#"
}