@server = http://localhost:3000/api

POST {{server}}/login
content-type: application/json

{
    "user": "laura.flores@nuevoamanecer.edu.mx",
    "password": "123456789Ab#"
}

###

POST {{server}}/login
content-type: application/json

{
    "user": "padre@nuevoamanecer.edu.mx",
    "password": "123456789Ab#"
}