@server = http://localhost:3000/api

GET {{server}}/parents

###

GET {{server}}/parents/1

###

POST {{server}}/parents
content-type: application/json

{
    "user": "padre@nuevoamanecer.edu.mx",
    "password": "123456789Ab#"
}