@server = http://localhost:3000/api

GET {{server}}/students

###

POST {{server}}/students/therapist/1
content-type: application/json

{
    "name": "Pedro Alonso Moreno Salcedo",
    "birthYear": 2003,
    "cognitiveLevel": "Such a low cognitive level",
    "maximumMinigameLevel": 2,
    "gender": "male",
    "diagnostic": "Very smart guy",
    "therapistId": 1,
    "parentId": 2
}