@server = http://localhost:3000/api

GET {{server}}/students

###

GET {{server}}/students/1

###

GET {{server}}/students?therapistId=1

###

GET {{server}}/students/parent/1

###

POST {{server}}/students
content-type: application/json

{
    "name": "Pedro Alonso Moreno Salcedo",
    "birthYear": 2003,
    "cognitiveLevel": "Such a low cognitive level",
    "maximumMinigameLevel": 2,
    "gender": "male",
    "description": "Very smart guy",
    "therapistId": 1
}

###
PUT {{server}}/students/1
content-type: application/json

{
    "name": "Felipe González",
    "birthYear": 2003,
    "cognitiveLevel": "Test",
    "maximumMinigameLevel": 4,
    "gender": "female",
    "description": "Hello world",
    "therapistId": 1
}

###

DELETE {{server}}/students/2